package objects

// Code generated from OCSF schema; DO NOT EDIT.

// Finding The Finding object describes metadata related to a security finding generated by
// a security tool or system.
type Finding struct {
	// The time when the finding was created.
	CreatedTime int64 `json:"created_time,omitempty"`

	// The time when the finding was created.
	CreatedTimeDt string `json:"created_time_dt,omitempty"`

	// The description of the reported finding.
	Desc string `json:"desc,omitempty"`

	// The time when the finding was first observed.
	FirstSeenTime int64 `json:"first_seen_time,omitempty"`

	// The time when the finding was first observed.
	FirstSeenTimeDt string `json:"first_seen_time_dt,omitempty"`

	// The time when the finding was most recently observed.
	LastSeenTime int64 `json:"last_seen_time,omitempty"`

	// The time when the finding was most recently observed.
	LastSeenTimeDt string `json:"last_seen_time_dt,omitempty"`

	// The time when the finding was last modified.
	ModifiedTime int64 `json:"modified_time,omitempty"`

	// The time when the finding was last modified.
	ModifiedTimeDt string `json:"modified_time_dt,omitempty"`

	// Details about the product that reported the finding.
	Product *Product `json:"product,omitempty"`

	// The unique identifier of the product that reported the finding.
	ProductUID string `json:"product_uid,omitempty"`

	// Describes events and/or other findings related to the finding as identified
	// by the security product. Note that these events may or may not be in OCSF.
	RelatedEvents []*RelatedEvent `json:"related_events,omitempty"`

	// Describes the recommended remediation steps to address identified issue(s).
	Remediation *Remediation `json:"remediation,omitempty"`

	// The URL pointing to the source of the finding.
	SrcURL string `json:"src_url,omitempty"`

	// Additional data supporting a finding as provided by security tool
	SupportingData interface{} `json:"supporting_data,omitempty"`

	// A title or a brief phrase summarizing the reported finding.
	Title string `json:"title,omitempty"`

	// One or more types of the reported finding.
	Types []string `json:"types,omitempty"`

	// The unique identifier of the reported finding.
	Uid string `json:"uid,omitempty"`
}
