package objects

// Code generated from OCSF schema; DO NOT EDIT.

// FindingInfo The Finding Information object describes metadata related to a security finding
// generated by a security tool or system.
type FindingInfo struct {
	// The analytic technique used to analyze and derive insights from the data or
	// information that led to the finding or conclusion.
	Analytic *Analytic `json:"analytic,omitempty"`

	// An Attack Graph describes possible routes an attacker could take through an
	// environment. It describes relationships between resources and their
	// findings, such as malware detections, vulnerabilities, misconfigurations,
	// and other security actions.
	AttackGraph *Graph `json:"attack_graph,omitempty"`

	// The https://attack.mitre.org MITRE ATT&CK® technique and associated tactics
	// related to the finding.
	Attacks []*Attack `json:"attacks,omitempty"`

	// The time when the finding was created.
	CreatedTime int64 `json:"created_time,omitempty"`

	// The time when the finding was created.
	CreatedTimeDt string `json:"created_time_dt,omitempty"`

	// A list of data sources utilized in generation of the finding.
	DataSources []string `json:"data_sources,omitempty"`

	// The description of the reported finding.
	Desc string `json:"desc,omitempty"`

	// The time when the finding was first observed. e.g. The time when a
	// vulnerability was first observed. <p>It can differ from the created_time
	// timestamp, which reflects the time this finding was created.</p>
	FirstSeenTime int64 `json:"first_seen_time,omitempty"`

	// The time when the finding was first observed. e.g. The time when a
	// vulnerability was first observed. <p>It can differ from the created_time
	// timestamp, which reflects the time this finding was created.</p>
	FirstSeenTimeDt string `json:"first_seen_time_dt,omitempty"`

	// The
	// https://www.lockheedmartin.com/en-us/capabilities/cyber/cyber-kill-chain.html
	// Cyber Kill Chain® provides a detailed description of each phase and its
	// associated activities within the broader context of a cyber attack.
	KillChain []*KillChainPhase `json:"kill_chain,omitempty"`

	// The time when the finding was most recently observed. e.g. The time when a
	// vulnerability was most recently observed. <p>It can differ from the
	// modified_time timestamp, which reflects the time this finding was last
	// modified.</p>
	LastSeenTime int64 `json:"last_seen_time,omitempty"`

	// The time when the finding was most recently observed. e.g. The time when a
	// vulnerability was most recently observed. <p>It can differ from the
	// modified_time timestamp, which reflects the time this finding was last
	// modified.</p>
	LastSeenTimeDt string `json:"last_seen_time_dt,omitempty"`

	// The time when the finding was last modified.
	ModifiedTime int64 `json:"modified_time,omitempty"`

	// The time when the finding was last modified.
	ModifiedTimeDt string `json:"modified_time_dt,omitempty"`

	// Details about the product that reported the finding.
	Product *Product `json:"product,omitempty"`

	// The unique identifier of the product that reported the finding.
	ProductUID string `json:"product_uid,omitempty"`

	// Other analytics related to this finding.
	RelatedAnalytics []*Analytic `json:"related_analytics,omitempty"`

	// Describes events and/or other findings related to the finding as identified
	// by the security product. Note that these events may or may not be in OCSF.
	RelatedEvents []*RelatedEvent `json:"related_events,omitempty"`

	// Number of related events or findings.
	RelatedEventsCount int64 `json:"related_events_count,omitempty"`

	// The URL pointing to the source of the finding.
	SrcURL string `json:"src_url,omitempty"`

	// The list of tags; {key:value} pairs associated with the finding.
	Tags []*KeyValueObject `json:"tags,omitempty"`

	// A title or a brief phrase summarizing the reported finding.
	Title string `json:"title,omitempty"`

	// The list of key traits or characteristics extracted from the finding.
	Traits []*Trait `json:"traits,omitempty"`

	// One or more types of the reported finding.
	Types []string `json:"types,omitempty"`

	// The unique identifier of the reported finding.
	Uid string `json:"uid,omitempty"`

	// The alternative unique identifier of the reported finding.
	UidAlt string `json:"uid_alt,omitempty"`
}
