package classes

// Code generated from OCSF schema; DO NOT EDIT.

import "github.com/veridian-sky/gocsf/objects"

// DataSecurityFinding A Data Security Finding describes detections or alerts generated by various data
// security products such as Data Loss Prevention (DLP), Data Classification,
// Secrets Management, Digital Rights Management (DRM), Data Security Posture
// Management (DSPM), and similar tools. These detections or alerts can be created
// using fingerprinting, statistical analysis, machine learning or other
// methodologies. The finding describes the actors and endpoints who accessed or
// own the sensitive data, as well as the resources which store the sensitive data.
// Note: if the event producer is a security control, the security_control profile
// should be applied and its attacks information, if present, should be duplicated
// into the finding_info object. Note: If the Finding is an incident, i.e. requires
// incident workflow, also apply the incident profile or aggregate this finding
// into an Incident Finding.
type DataSecurityFinding struct {
	// The normalized caption of action_id.
	Action string `json:"action,omitempty"`

	// The action taken by a control or other policy-based system leading to an
	// outcome or disposition. An unknown action may still correspond to a known
	// disposition. Refer to disposition_id for the outcome of the action.
	ActionID int `json:"action_id,omitempty"`

	// The normalized identifier of the Data Security Finding activity.
	ActivityID int `json:"activity_id,omitempty"`

	// The Data Security finding activity name, as defined by the activity_id.
	ActivityName string `json:"activity_name,omitempty"`

	// Describes details about the actor implicated in the data security finding.
	// Either an actor that owns a particular digital file or information store, or
	// an actor which accessed classified or sensitive data.
	Actor *objects.Actor `json:"actor,omitempty"`

	// Describes details about a typical API (Application Programming Interface)
	// call.
	Api *objects.Api `json:"api,omitempty"`

	// The details of the user assigned to an Incident.
	Assignee *objects.User `json:"assignee,omitempty"`

	// The details of the group assigned to an Incident.
	AssigneeGroup *objects.Group `json:"assignee_group,omitempty"`

	// An array of MITRE ATT&CK® objects describing identified tactics, techniques
	// & sub-techniques. The objects are compatible with MITRE ATLAS™ tactics,
	// techniques & sub-techniques.
	Attacks []*objects.Attack `json:"attacks,omitempty"`

	// Provides details about an authorization, such as authorization outcome, and
	// any associated policies related to the activity/event.
	Authorizations []*objects.Authorization `json:"authorizations,omitempty"`

	// The event category name, as defined by category_uid value: Findings.
	CategoryName string `json:"category_name,omitempty"`

	// The category unique identifier of the event.
	CategoryUID int `json:"category_uid,omitempty"`

	// The event class name, as defined by class_uid value: Data Security Finding.
	ClassName string `json:"class_name,omitempty"`

	// The unique identifier of a class. A class describes the attributes available
	// in an event.
	ClassUID int `json:"class_uid,omitempty"`

	// Describes details about the Cloud environment where the event was originally
	// created or logged.
	Cloud *objects.Cloud `json:"cloud,omitempty"`

	// A user provided comment about the finding.
	Comment string `json:"comment,omitempty"`

	// The confidence, normalized to the caption of the confidence_id value. In the
	// case of 'Other', it is defined by the event source.
	Confidence string `json:"confidence,omitempty"`

	// The normalized confidence refers to the accuracy of the rule that created
	// the finding. A rule with a low confidence means that the finding scope is
	// wide and may create finding reports that may not be malicious in nature.
	ConfidenceID int `json:"confidence_id,omitempty"`

	// The confidence score as reported by the event source.
	ConfidenceScore int64 `json:"confidence_score,omitempty"`

	// The number of times that events in the same logical group occurred during
	// the event Start Time to End Time period.
	Count int64 `json:"count,omitempty"`

	// The Data Security object describes the characteristics, techniques and
	// content of a Data Loss Prevention (DLP), Data Loss Detection (DLD), Data
	// Classification, or similar tools' finding, alert, or detection mechanism(s).
	DataSecurity *objects.DataSecurity `json:"data_security,omitempty"`

	// Describes the database where classified or sensitive data is stored in, or
	// was accessed from. Databases are typically datastore services that contain
	// an organized collection of structured and/or semi-structured data.
	Database *objects.Database `json:"database,omitempty"`

	// Describes the databucket where classified or sensitive data is stored in, or
	// was accessed from. The data bucket object is a basic container that holds
	// data, typically organized through the use of data partitions.
	Databucket *objects.Databucket `json:"databucket,omitempty"`

	// Describes the device where classified or sensitive data is stored in, or was
	// accessed from.
	Device *objects.Device `json:"device,omitempty"`

	// The disposition name, normalized to the caption of the disposition_id value.
	// In the case of 'Other', it is defined by the event source.
	Disposition string `json:"disposition,omitempty"`

	// Describes the outcome or action taken by a security control, such as access
	// control checks, malware detections or various types of policy violations.
	DispositionID int `json:"disposition_id,omitempty"`

	// Describes the endpoint where classified or sensitive data is stored in, or
	// was accessed from.
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`

	// The event duration or aggregate time, the amount of time the event covers
	// from start_time to end_time in milliseconds.
	Duration int64 `json:"duration,omitempty"`

	// The time of the most recent event included in the finding.
	EndTime int64 `json:"end_time,omitempty"`

	// The time of the most recent event included in the finding.
	EndTimeDt string `json:"end_time_dt,omitempty"`

	// The additional information from an external data source, which is associated
	// with the event or a finding. For example add location information for the IP
	// address in the DNS answers:</p>[{"name": "answers.ip", "value":
	// "92.24.47.250", "type": "location", "data": {"city": "Socotra", "continent":
	// "Asia", "coordinates": [-25.4153, 17.0743], "country": "YE", "desc":
	// "Yemen"}}]
	Enrichments []*objects.Enrichment `json:"enrichments,omitempty"`

	// Describes a file that contains classified or sensitive data.
	File *objects.File `json:"file,omitempty"`

	// Describes the supporting information about a generated finding.
	FindingInfo *objects.FindingInfo `json:"finding_info,omitempty"`

	// The firewall rule that pertains to the control that triggered the event, if
	// applicable.
	FirewallRule *objects.FirewallRule `json:"firewall_rule,omitempty"`

	// The impact , normalized to the caption of the impact_id value. In the case
	// of 'Other', it is defined by the event source.
	Impact string `json:"impact,omitempty"`

	// The normalized impact of the incident or finding. Per NIST, this is the
	// magnitude of harm that can be expected to result from the consequences of
	// unauthorized disclosure, modification, destruction, or loss of information
	// or information system availability.
	ImpactID int `json:"impact_id,omitempty"`

	// The impact as an integer value of the finding, valid range 0-100.
	ImpactScore int64 `json:"impact_score,omitempty"`

	// Indicates that the event is considered to be an alertable signal. For
	// example, an activity_id of 'Create' could constitute an alertable signal and
	// the value would be true, while 'Close' likely would not and either omit the
	// attribute or set its value to false. Note that other events with the
	// security_control profile may also be deemed alertable signals and may also
	// carry is_alert = true attributes.
	IsAlert bool `json:"is_alert,omitempty"`

	// A determination based on analytics as to whether a potential breach was
	// found.
	IsSuspectedBreach bool `json:"is_suspected_breach,omitempty"`

	// A list of Malware objects, describing details about the identified malware.
	Malware []*objects.Malware `json:"malware,omitempty"`

	// Describes details about the scan job that identified malware on the target
	// system.
	MalwareScanInfo *objects.MalwareScanInfo `json:"malware_scan_info,omitempty"`

	// The description of the event/finding, as defined by the source.
	Message string `json:"message,omitempty"`

	// The metadata associated with the event or a finding.
	Metadata *objects.Metadata `json:"metadata,omitempty"`

	// The observables associated with the event or a finding.
	Observables []*objects.Observable `json:"observables,omitempty"`

	// The OSINT (Open Source Intelligence) object contains details related to an
	// indicator such as the indicator itself, related indicators, geolocation,
	// registrar information, subdomains, analyst commentary, and other contextual
	// information. This information can be used to further enrich a detection or
	// finding by providing decisioning support to other analysts and engineers.
	Osint []*objects.Osint `json:"osint,omitempty"`

	// The policy that pertains to the control that triggered the event, if
	// applicable. For example the name of an anti-malware policy or an access
	// control policy.
	Policy *objects.Policy `json:"policy,omitempty"`

	// The priority, normalized to the caption of the priority_id value. In the
	// case of 'Other', it is defined by the event source.
	Priority string `json:"priority,omitempty"`

	// The normalized priority. Priority identifies the relative importance of the
	// incident or finding. It is a measurement of urgency.
	PriorityID int `json:"priority_id,omitempty"`

	// The raw event/finding data as received from the source.
	RawData string `json:"raw_data,omitempty"`

	// The hash, which describes the content of the raw_data field.
	RawDataHash *objects.Fingerprint `json:"raw_data_hash,omitempty"`

	// The size of the raw data which was transformed into an OCSF event, in bytes.
	RawDataSize int64 `json:"raw_data_size,omitempty"`

	// Describes details about additional resources, where classified or sensitive
	// data is stored in, or was accessed from. <p> You can populate this object,
	// if the specific resource type objects available in the class (database,
	// databucket, table, file) aren't sufficient; OR You can also choose to
	// duplicate uid, name of the specific resources objects, for a consistent
	// access to resource uids across all findings.
	Resources []*objects.ResourceDetails `json:"resources,omitempty"`

	// Describes the risk associated with the finding.
	RiskDetails string `json:"risk_details,omitempty"`

	// The risk level, normalized to the caption of the risk_level_id value.
	RiskLevel string `json:"risk_level,omitempty"`

	// The normalized risk level id.
	RiskLevelID int `json:"risk_level_id,omitempty"`

	// The risk score as reported by the event source.
	RiskScore int64 `json:"risk_score,omitempty"`

	// The event/finding severity, normalized to the caption of the severity_id
	// value. In the case of 'Other', it is defined by the source.
	Severity string `json:"severity,omitempty"`

	// <p>The normalized identifier of the event/finding severity.</p>The
	// normalized severity is a measurement the effort and expense required to
	// manage and resolve an event or incident. Smaller numerical values represent
	// lower impact events, and larger numerical values represent higher impact
	// events.
	SeverityID int `json:"severity_id,omitempty"`

	// Details about the source endpoint where classified or sensitive data was
	// accessed from.
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`

	// A Url link used to access the original incident.
	SrcURL string `json:"src_url,omitempty"`

	// The time of the least recent event included in the finding.
	StartTime int64 `json:"start_time,omitempty"`

	// The time of the least recent event included in the finding.
	StartTimeDt string `json:"start_time_dt,omitempty"`

	// The normalized status of the Finding set by the consumer normalized to the
	// caption of the status_id value. In the case of 'Other', it is defined by the
	// source.
	Status string `json:"status,omitempty"`

	// The event status code, as reported by the event source.<br /><br />For
	// example, in a Windows Failed Authentication event, this would be the value
	// of 'Failure Code', e.g. 0x18.
	StatusCode string `json:"status_code,omitempty"`

	// The status detail contains additional information about the event/finding
	// outcome.
	StatusDetail string `json:"status_detail,omitempty"`

	// The normalized status identifier of the Finding, set by the consumer.
	StatusID int `json:"status_id,omitempty"`

	// Describes the table where classified or sensitive data is stored in, or was
	// accessed from. The table object represents a table within a structured
	// relational database, warehouse, lake, or similar.
	Table *objects.Table `json:"table,omitempty"`

	// The linked ticket in the ticketing system.
	Ticket *objects.Ticket `json:"ticket,omitempty"`

	// The associated ticket(s) in the ticketing system. Each ticket contains
	// details like ticket ID, status, etc.
	Tickets []*objects.Ticket `json:"tickets,omitempty"`

	// The normalized event occurrence time or the finding creation time.
	Time int64 `json:"time,omitempty"`

	// The normalized event occurrence time or the finding creation time.
	TimeDt string `json:"time_dt,omitempty"`

	// The number of minutes that the reported event time is ahead or behind UTC,
	// in the range -1,080 to +1,080.
	TimezoneOffset int64 `json:"timezone_offset,omitempty"`

	// The event/finding type name, as defined by the type_uid.
	TypeName string `json:"type_name,omitempty"`

	// The event/finding type ID. It identifies the event's semantics and
	// structure. The value is calculated by the logging system as: class_uid * 100
	// + activity_id.
	TypeUID int `json:"type_uid,omitempty"`

	// The attributes that are not mapped to the event schema. The names and values
	// of those attributes are specific to the event source.
	Unmapped *objects.Object `json:"unmapped,omitempty"`

	// The Vendor Attributes object can be used to represent values of attributes
	// populated by the Vendor/Finding Provider. It can help distinguish between
	// the vendor-provided values and consumer-updated values, of key attributes
	// like severity_id. The original finding producer should not populate this
	// object. It should be populated by consuming systems that support data
	// mutability.
	VendorAttributes *objects.VendorAttributes `json:"vendor_attributes,omitempty"`

	// The verdict assigned to an Incident finding.
	Verdict string `json:"verdict,omitempty"`

	// The normalized verdict of an Incident.
	VerdictID int `json:"verdict_id,omitempty"`
}
